### PR TITLE
[FLINK-10911][scala-shell] Draft scala-shell 2.12 PR with case classes using KryoSerializer

### PR DESCRIPTION
**Pull request by tobymiller**

### CODE REVIEW

**Comment by dawidwys** [comment]
Hey @tobymiller. Please do not open PRs against this repo. If you want to contribute to Flink you should open a PR against: https://github.com/apache/flink

This repository is an internal one, used purely for running CI on Azure for branches in the original repo.

**Comment by tobymiller** [comment]
@dawidwys Sorry - I was following the instructions [here](https://cwiki.apache.org/confluence/display/FLINK/Azure+Pipelines#AzurePipelines-AzurePipelineUsageRestrictions) in order to run the CI against my PR while waiting for Azure to approve my account. Are these instructions no longer valid?

**Comment by tobymiller** [comment]
(Without spamming with an unfinished PR against real Flink)

**Comment by dawidwys** [comment]
Hmm, @tobymiller I was not aware it was described in that page :( I guess it's ok if it is described there.

**Comment by tobymiller** [comment]
@dawidwys No worries. I have what I need from Azure now so I can close this. Sorry to disturb you!

**Pull request closed without merging**
